//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTilausDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kokonaismyynti_apu_taulu
    {
        public long riviID { get; set; }
        public string Nimi { get; set; }
        public Nullable<int> DailySales { get; set; }
    }
}
