//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTilausDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Logins
    {
        public int LoginId { get; set; }
        [Required(ErrorMessage = "Anna käyttäjätunnus!")] //Vaaditaan login toimintoja varten
        public string UserName { get; set; }
        [DataType(DataType.Password)] //Kertoo ohjelmalle että annettava tieto on salasana.
        [Required(ErrorMessage = "Anna salasana!")] //Annetaan virheilmoitus, jos salasanaa ei annettu.
        public string PassWord { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
